host: codespaces-c89ec1
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                        count
-----------------------  -------
all                            1
run_Fedup_HefQuin_query        3
total                          4

Select jobs to execute...
Execute 1 jobs...

[Tue Mar 25 22:36:13 2025]
localrule run_Fedup_HefQuin_query:
    input: /workspaces/P-TER/virtuoso-opensource-7.2.7, /workspaces/P-TER/virtuoso-opensource-7.2.7/var/lib/virtuoso/db/fedup.ini, /workspaces/P-TER/fedup-queries/q05a.sparql
    output: output/rdfs/FedUp-HefQuin/q05a.1.csv, output/rdfs/FedUp-HefQuin/q05a.1.json, output/rdfs/FedUp-HefQuin/q05a.1.txt
    jobid: 1
    reason: Missing output files: output/rdfs/FedUp-HefQuin/q05a.1.csv
    wildcards: workload=rdfs, query=q05a, run=1
    priority: 50
    resources: tmpdir=/tmp

[Tue Mar 25 22:36:16 2025]
Finished job 1.
1 of 4 steps (25%) done
Select jobs to execute...
Execute 1 jobs...

[Tue Mar 25 22:36:16 2025]
localrule run_Fedup_HefQuin_query:
    input: /workspaces/P-TER/virtuoso-opensource-7.2.7, /workspaces/P-TER/virtuoso-opensource-7.2.7/var/lib/virtuoso/db/fedup.ini, /workspaces/P-TER/fedup-queries/q05a.sparql
    output: output/rdfs/FedUp-HefQuin/q05a.3.csv, output/rdfs/FedUp-HefQuin/q05a.3.json, output/rdfs/FedUp-HefQuin/q05a.3.txt
    jobid: 3
    reason: Missing output files: output/rdfs/FedUp-HefQuin/q05a.3.csv
    wildcards: workload=rdfs, query=q05a, run=3
    priority: 50
    resources: tmpdir=/tmp

[Tue Mar 25 22:36:19 2025]
Finished job 3.
2 of 4 steps (50%) done
Select jobs to execute...
Execute 1 jobs...

[Tue Mar 25 22:36:19 2025]
localrule run_Fedup_HefQuin_query:
    input: /workspaces/P-TER/virtuoso-opensource-7.2.7, /workspaces/P-TER/virtuoso-opensource-7.2.7/var/lib/virtuoso/db/fedup.ini, /workspaces/P-TER/fedup-queries/q05a.sparql
    output: output/rdfs/FedUp-HefQuin/q05a.2.csv, output/rdfs/FedUp-HefQuin/q05a.2.json, output/rdfs/FedUp-HefQuin/q05a.2.txt
    jobid: 2
    reason: Missing output files: output/rdfs/FedUp-HefQuin/q05a.2.csv
    wildcards: workload=rdfs, query=q05a, run=2
    priority: 50
    resources: tmpdir=/tmp

[Tue Mar 25 22:36:24 2025]
Finished job 2.
3 of 4 steps (75%) done
Select jobs to execute...
Execute 1 jobs...

[Tue Mar 25 22:36:24 2025]
localrule all:
    input: config/largerdfbench/graphs.txt, config/rdfs/endpoints.txt, output/rdfs/FedUp-HefQuin/q05a.1.csv, output/rdfs/FedUp-HefQuin/q05a.2.csv, output/rdfs/FedUp-HefQuin/q05a.3.csv
    output: output/data.csv
    jobid: 0
    reason: Input files updated by another job: output/rdfs/FedUp-HefQuin/q05a.2.csv, output/rdfs/FedUp-HefQuin/q05a.1.csv, output/rdfs/FedUp-HefQuin/q05a.3.csv; Set of input files has changed since last execution
    resources: tmpdir=/tmp

Terminating processes on user request, this might take some time.
Traceback (most recent call last):

  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/snakemake/executors/local.py", line 232, in spawn_job
    subprocess.check_call(cmd, shell=True)

  File "/usr/local/python/3.12.1/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command 'cd /workspaces/P-TER && /usr/local/python/3.12.1/bin/python3 -m snakemake --snakefile '/workspaces/P-TER/Snakefile' --target-jobs 'all:' --allowed-rules all --cores 1 --attempt 1 --force-use-threads  --force --target-files-omit-workdir-adjustment --keep-storage-local-copies --max-inventory-time 0 --nocolor --notemp --no-hooks --nolock --ignore-incomplete --rerun-triggers input mtime code params software-env --conda-frontend 'conda' --shared-fs-usage sources input-output storage-local-copies software-deployment persistence source-cache --wrapper-prefix 'https://github.com/snakemake/snakemake-wrappers/raw/' --latency-wait 5 --scheduler 'greedy' --local-storage-prefix .snakemake/storage --scheduler-solver-path '/usr/local/python/3.12.1/bin' --default-resources base64//dG1wZGlyPXN5c3RlbV90bXBkaXI= --quiet progress rules --mode 'subprocess' --local-groupid 'local'' died with <Signals.SIGINT: 2>.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/python/3.12.1/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)

  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/snakemake/executors/local.py", line 234, in spawn_job
    raise SpawnedJobError()

snakemake.exceptions.SpawnedJobError

[Tue Mar 25 22:36:25 2025]
Error in rule all:
    jobid: 0
    input: config/largerdfbench/graphs.txt, config/rdfs/endpoints.txt, output/rdfs/FedUp-HefQuin/q05a.1.csv, output/rdfs/FedUp-HefQuin/q05a.2.csv, output/rdfs/FedUp-HefQuin/q05a.3.csv
    output: output/data.csv

Complete log: .snakemake/log/2025-03-25T223613.420059.snakemake.log
WorkflowError:
At least one job did not complete successfully.
